// Generated by CoffeeScript 1.4.0
(function() {
  var APP_NAME, App, dev, getMessage, syncStorage;

  dev = true;

  APP_NAME = "taobao-currency-converter";

  syncStorage = chrome.storage[dev ? 'local' : 'sync'];

  getMessage = chrome.i18n.getMessage;

  window.onload = function() {
    window.app = new App;
    return syncStorage.get(APP_NAME, function(items) {
      console.log('data from syncStorage', items[APP_NAME]);
      if (items[APP_NAME]) {
        app.options = items[APP_NAME];
      }
      return app.init();
    });
  };

  App = (function() {

    function App() {}

    App.prototype.options = {};

    App.prototype.init = function() {
      console.log(APP_NAME + ' start');
      fx.base = "RUR";
      fx.rates = {
        CNY: 0.198514907,
        USD: 0.032001,
        RUR: 1
      };
      return $(".price").each(function() {
        var newText, text;
        text = $(this).text();
        newText = "";
        newText += app.convert(text.replace(/￥/g, ""), "RUR");
        newText += " ";
        newText += app.convert(text.replace(/￥/g, ""), "USD");
        return $(this).html(newText);
      });
    };

    App.prototype.convert = function(sum, toCurrency) {
      sum = fx.convert(sum, {
        from: "CNY",
        to: toCurrency
      });
      return accounting.formatMoney(sum, {
        symbol: toCurrency,
        format: "%v %s"
      });
    };

    return App;

  })();

  if (!dev) {
    console.log = console.error = function() {};
  }

}).call(this);
